1. Extract data from the given SalaryGender CSV file and store the data from each column in a separate NumPy array.


In [1]:
import numpy as np


In [2]:
# Load the CSV file using numpy.genfromtxt()
data = np.genfromtxt('SalaryGender.csv', delimiter=',', names=True, dtype=None)

# Extract data from each column into separate NumPy arrays
salary = data['Salary']
gender = data['Gender']
age = data['Age']
phd = data['PhD']

# Print the first few elements of each array
print("Salary:", salary[:5])
print("Gender:", gender[:5])
print("Age:", age[:5])
print("PhD:", phd[:5])

Salary: [140.   30.   35.1  30.   80. ]
Gender: [1 0 0 1 0]
Age: [47 65 56 23 53]
PhD: [1 1 0 0 1]


2.Find:
1. The number of men with a PhD
2. The number of women with a PhD

In [6]:
# Filter data for men with a PhD
men_with_phd = data[(data['Gender'] == 1) & (data['PhD'] == 1)]

# Count the number of men with a PhD
num_men_with_phd = len(men_with_phd)

print("Number of men with a PhD:", num_men_with_phd)


# Filter data for women with a PhD
women_with_phd = data[(data['Gender'] == 0) & (data['PhD'] == 1)]

# Count the number of women with a PhD
num_women_with_phd = len(women_with_phd)

print("Number of women with a PhD:", num_women_with_phd)


Number of men with a PhD: 24
Number of women with a PhD: 15


3. Use SalaryGender CSV file. Store the “Age” and “Ph.D.” columns in one DataFrame and delete the data of all people who don’t have a PhD.

In [7]:
# Extract the 'Age' and 'PhD' columns into separate NumPy arrays
age = data['Age']
phd = data['PhD']

# Filter the data to keep only the rows where 'PhD' is 1 (i.e., people who have a PhD)
phd_indices = np.where(phd == 1)
age_phd_data = data[phd_indices]

print(age_phd_data)

[(140. , 1, 47, 1) ( 30. , 0, 65, 1) ( 80. , 0, 53, 1) (125. , 1, 44, 1)
 ( 51. , 1, 63, 1) (150. , 1, 60, 1) ( 84. , 0, 47, 1) (190. , 1, 66, 1)
 ( 74. , 1, 45, 1) ( 15.2, 1, 66, 1) ( 28.6, 1, 36, 1) ( 72. , 0, 51, 1)
 ( 81. , 1, 65, 1) (100. , 0, 45, 1) ( 90. , 0, 52, 1) ( 90. , 0, 54, 1)
 ( 63. , 1, 34, 1) ( 92. , 0, 58, 1) (106. , 1, 77, 1) ( 32. , 0, 48, 1)
 ( 55. , 1, 49, 1) ( 28. , 0, 65, 1) ( 84. , 0, 49, 1) (160. , 1, 61, 1)
 ( 65. , 0, 43, 1) (102. , 1, 66, 1) ( 55. , 1, 56, 1) (152. , 1, 71, 1)
 ( 30. , 1, 69, 1) (120. , 1, 58, 1) ( 36. , 1, 32, 1) ( 96. , 1, 33, 1)
 ( 38. , 0, 32, 1) ( 72. , 1, 42, 1) ( 41. , 0, 51, 1) ( 89. , 1, 71, 1)
 ( 52. , 1, 55, 1) ( 66. , 0, 55, 1) (152. , 1, 56, 1)]


4. Calculate the total number of people who have a Ph.D.degreefrom the SalaryGender CSV file.

In [8]:
 # Count the number of occurrences where 'PhD' is 1 (i.e., people who have a Ph.D. degree)
total_phd = np.count_nonzero(phd == 1)

print("Total number of people with a Ph.D. degree:", total_phd)

Total number of people with a Ph.D. degree: 39


5. How  do  you  Count  The  Number  Of  Times  Each  Value  Appears  In  An  Array  Of Integers?[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1,1, 9]Answer should be array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1]) which means 0 comes 4 times, 1 comes 2 times, 2 comes 1 time, 3 comes 1 time and so on.

In [9]:
# Define the array of integers
array = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])

# Use numpy.bincount() to count the occurrences of each value
counts = np.bincount(array)

print(counts)

[4 2 1 1 3 2 0 0 0 1]


6. Create a numpy array [[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]) and filter the elements greater than 5.

In [10]:
# Create the numpy array
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

# Filter the elements greater than 5
filtered_arr = arr[arr > 5]

print(filtered_arr)

[ 6  7  8  9 10 11]


7. Create a numpy array having NaN (Not a Number) and print it.array([ nan,   1.,   2.,  nan,   3.,   4.,   5.])Print the same array omitting all elements which are nan.

In [11]:
# Create the numpy array with NaN values
arr = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])

# Filter out the NaN values
filtered_arr = arr[~np.isnan(arr)]

print(filtered_arr)

[1. 2. 3. 4. 5.]


8.Create  a  10x10  array  with  random  values  and  find  the  minimum  and  maximum values.


In [12]:
# Create a 10x10 array with random values between 0 and 1
array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.004980775379779923
Maximum value: 0.9897295925173951


9.Create a random vector of size 30 and find the mean value.

In [13]:
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)

Mean value: 0.4639492204068985


10. Create a numpy array having elements 0 to 10 And negate all the elements between 3 and 9.

In [14]:
arr = np.arange(11)

# Negate the elements between 3 and 9
arr[(arr > 3) & (arr < 9)] *= -1

print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


11. Create a random array of 3 rows and 3 columns and sort it according to 1stcolumn, 2ndcolumn,or 3rdcolumn.

In [15]:
array = np.random.rand(3, 3)

# Define the column index to sort by (0 for the 1st column, 1 for the 2nd column, 2 for the 3rd column)
column_index = 0

# Sort the array based on the specified column
sorted_array = array[array[:, column_index].argsort()]

print("Original array:")
print(array)
print("\nSorted array based on column", column_index + 1, ":")
print(sorted_array)


Original array:
[[0.68665177 0.10159502 0.5821328 ]
 [0.92570917 0.69590305 0.18426557]
 [0.36867839 0.10725995 0.08882793]]

Sorted array based on column 1 :
[[0.36867839 0.10725995 0.08882793]
 [0.68665177 0.10159502 0.5821328 ]
 [0.92570917 0.69590305 0.18426557]]


12. Create a four dimensions array to get the sum over the last two axesat once.

In [ ]:
array = np.random.rand(2, 3, 4, 5)

# Get the sum over the last two axes at once
sum_over_last_two_axes = np.sum(array, axis=(-2, -1))

print("Original array shape:", array.shape)
print("Sum over the last two axes shape:", sum_over_last_two_axes.shape)
print("Sum over the last two axes:")
print(sum_over_last_two_axes)