In [3]:
# Creating NumPy array--> will contain the data.
# Numpy array follow the concept of indexing.

import numpy as np

#ar = np.array([45,36,98,75,23,41,52,63])
ar = np.array([45,36,98,75,23,41,52,63,'abc',45.3])
print(ar)
print(type(ar))
print(ar.dtype)


['45' '36' '98' '75' '23' '41' '52' '63' 'abc' '45.3']
<class 'numpy.ndarray'>
<U32


In [6]:
# arange(start. stop, step)

ar = np.arange(10,20)
print(ar)
print(type(ar))


ar = np.arange(10,20,2)
print(ar)
print(type(ar))

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[10 12 14 16 18]
<class 'numpy.ndarray'>


In [9]:
# One dimentional array= the data is expanded in one direction.
print(ar)
print(ar[2])

[10 12 14 16 18]
14


In [14]:
# 2D array: [rows and columns]

ar = np.array([[10,20,30,100],[40,50,60,200],[70,80,90,300]])
print(ar)
print("Number of dim is:", ar.ndim)
print("Shape: rows and cols:", ar.shape)
print("Size the number of elements inside the array:", ar.size)


[[ 10  20  30 100]
 [ 40  50  60 200]
 [ 70  80  90 300]]
Number of dim is: 2
Shape: rows and cols: (3, 4)
Size the number of elements inside the array: 12


In [15]:
# Indexing in 2D arrays: always row comes first.
print(ar[1][2])

60


In [16]:
for i in ar:
    print(i)

[ 10  20  30 100]
[ 40  50  60 200]
[ 70  80  90 300]


In [21]:
# nditer will iterate through the array one by one
ind = 0
for i in np.nditer(ar):
    print(f"Index:{ind} Item:{i}")
    ind+=1

Index:0 Item:10
Index:1 Item:20
Index:2 Item:30
Index:3 Item:100
Index:4 Item:40
Index:5 Item:50
Index:6 Item:60
Index:7 Item:200
Index:8 Item:70
Index:9 Item:80
Index:10 Item:90
Index:11 Item:300


In [23]:
# Matrix
ar1 = np.array([[1,2,3],[4,5,6]])
ar2 = np.array([[10,11],[20,21],[30,31]])
print(ar1)
ar3 = np.dot(ar1,ar2)
print(ar3)

[[1 2 3]
 [4 5 6]]
[[140 146]
 [320 335]]


In [25]:
# Import/export data from a csv file:loadtxt(), savetxt()
# Numpy can only work with csv files.
# To load only one column, we have to pass the index number of the column

data = np.loadtxt("marks.csv", delimiter=',',usecols=(5),skiprows=1, dtype='int')
print(data)






[420 280 350 269 317 470 333 365 305 350 460 474 409 377 415 382 298 462
 370 313 464 302 252 259 308 392 424 403 370 328 398 434 291 472 263 439
 464 449 401 364 296 292 438 357 331 317 429 407 321 274 447 274 437 411
 257 310 396 270 311 459 378 316 283 266 381 409 313 306 448 348 292 400
 352 441 428 309 441 439 264 281 302 432 423 336 383 321 469 270 341 281
 403 333 323 348 345 397 449 261 456 370 322 379 446 404 301 254 351 444
 264 286 463 273 316 324 465 398 324 340 414 346 408 332 394 474 398 262
 410 391 444 461]


In [30]:
# Useful functions in Numpy

print("Sum:", data.sum())          #adds up all the values in the dataset.
print("Max:", data.max())
print("Min:", data.min())
print("Average:", data.mean())
print("Standard Deviation:", data.std())
print("Variance:", data.var())     #Square root of the variance

Sum: 47356
Max: 474
Min: 252
Average: 364.2769230769231
Standard Deviation: 66.17947803971762
Variance: 4379.723313609467


In [35]:
# Reshaping in Numpy array

ar = np.array([36,87,51,21,96,32])
print(ar.shape)
#2,3

ar_new = ar.reshape(2,3)
print(ar_new)

#ar_new = ar.reshape(3,3) error!
#print(ar_new)

(6,)
[[36 87 51]
 [21 96 32]]


In [39]:
# Transpose
ar = np.array([[10,11],[20,21],[30,31]])
print(ar)
print(ar.transpose)


[[10 11]
 [20 21]
 [30 31]]
<built-in method transpose of numpy.ndarray object at 0x7fa46f183870>


In [38]:
ar = np.array([36,87,51,21,96,32])
print(ar)
print(ar.reshape(-1,1))  #converting into one dimensioal array

[36 87 51 21 96 32]
[[36]
 [87]
 [51]
 [21]
 [96]
 [32]]


In [ ]:
# Explore stack() function and fancy indexing


In [42]:
# Broadcasting operations

lst = [10,20,30,40,50]
print(lst*2)     # will repeat the array items.

ar = np.array([10,20,30,40,50])
print(ar*2)      # will perform the operation directly on the object.
print(ar**3)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 20  40  60  80 100]
[  1000   8000  27000  64000 125000]
